apiVersion: v1
kind: Service
metadata:
  name: {{ include "appserver-chart.fullname" . }}-service
  labels:
    {{- include "appserver-chart.labels" . | nindent 4 }}
  {{- if .Values.namespaceBase.enabled }}
  namespace: {{ .Values.namespaceBase.name }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: {{ .Values.service.portName }}
  selector:
    {{- include "appserver-chart.selectorLabels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
