apiVersion: v1
kind: Secret
metadata:
  name: video-course-database-secret
type: Opaque
stringData:
  POSTGRES_USER: "videocoursepostgres"
  POSTGRES_PASSWORD: "videocoursepostgres@123"
  POSTGRES_DB: "videocoursedb"