# Default values for portainer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# If enterpriseEdition is enabled, then use the values below _instead_ of those in .image
enterpriseEdition: 
  enabled: false
  image:
    repository: portainer/portainer-ee
    tag: 2.19.5
    pullPolicy: Always

image:
  repository: portainer/portainer-ce
  tag: 2.19.5
  pullPolicy: Always

imagePullSecrets: []

nodeSelector: {}

serviceAccount:
  annotations: {}
  name: portainer-sa-clusteradmin

service:
  # Set the httpNodePort and edgeNodePort only if the type is NodePort
  # For Ingress, set the type to be ClusterIP and set ingress.enabled to true
  # For Cloud Providers, set the type to be LoadBalancer
  type: ClusterIP
  httpPort: 9000
  httpsPort: 9443
  httpNodePort: 30777
  httpsNodePort: 30779
  edgePort: 8000
  edgeNodePort: 30776
  annotations: {}

tls:
  # If set, Portainer will be configured to use TLS only
  force: true
  # If set, will mount the existing secret into the pod
  existingSecret: ""

mtls:
  # If set, Portainer will be configured to use mTLS only
  enable: false
  # If set, will mount the existing secret into the pod
  existingSecret: ""

feature:
  flags: []

ingress:
  enabled: true
  ingressClassName: ""
  annotations: 
    # kubernetes.io/ingress.class: nginx
    # Only use below if tls.force=true
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingressClassName: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  # Note: Hosts and paths are of type array
  hosts:
    - host: portainer.cheakautomate.online
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
  - secretName: portainer-chart-tls
    hosts:
      - portainer.cheakautomate.online

resources: {}

persistence:
  enabled: false
  size: "10Gi"
  annotations: {}
  storageClass: 
  existingClaim:
